#ifndef RTW_HEADER_power_FCHPS_MEA_acc_types_h_
#define RTW_HEADER_power_FCHPS_MEA_acc_types_h_
#include "rtwtypes.h"
#include "multiword_types.h"
typedef struct P_Subsystempi2delay_power_FCHPS_MEA_T_
P_Subsystempi2delay_power_FCHPS_MEA_T ; typedef struct
P_Subsystem1_power_FCHPS_MEA_T_ P_Subsystem1_power_FCHPS_MEA_T ; typedef
struct P_power_FCHPS_MEA_T_ P_power_FCHPS_MEA_T ;
#endif
