@echo off
set "VSCMD_START_DIR=%CD%"
call "D:\Visual Studio\IDE\VC\Auxiliary\Build\VCVARSALL.BAT" amd64

cd .
nmake -f fast_powertrain.mk  NON_ANSI_TRIG_FCN=1 RSIM_SOLVER_SELECTION=2 PCMATLABROOT="G:\\Matlab_2b\\software" EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 TMW_EXTMODE_TESTING=0 RSIM_PARAMETER_LOADING=1 OPTS="-DTGTCONN -DNRT -DRSIM_PARAMETER_LOADING -DRSIM_WITH_SL_SOLVER -DENABLE_SLEXEC_SSBRIDGE=1 -DMODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 -DON_TARGET_WAIT_FOR_START=0 -DTID01EQ=1"
@if errorlevel 1 goto error_exit
exit 0

:error_exit
echo The make command returned an error of %errorlevel%
exit 1